import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { hasReviewScore, scoreColors, cardFilename, cleanCardText, fitText, wrapLines } from './instagram-card.js';
for (const file of ['instagram-card.js','instagram-share.js']) new vm.SourceTextModule(fs.readFileSync(file,'utf8'));
for (const score of [null,undefined,'',NaN,-1,101,'abc']) assert.equal(hasReviewScore({reviewScore:score}),false);
for (const score of [0,49,50,69,70,100]) assert.equal(hasReviewScore({reviewScore:score}),true);
assert.equal(scoreColors(49)[0],'#f5988c');
assert.equal(scoreColors(50)[0],'#f3d36b');
assert.equal(scoreColors(69)[0],'#f3d36b');
assert.equal(scoreColors(70)[0],'#a4dd74');
assert.match(cardFilename({title:'Notícia: música / cinema?',reviewScore:null}),/^marte-alma-noticia-noticia-musica-cinema-1080x1350\.png$/);
assert.equal(cleanCardText('**Olá** [mundo](https://example.com) <b>hoje</b>'),'Olá mundo hoje');
const context={font:'',measureText(text){return {width:Array.from(text).length*Number(this.font.match(/(\d+)px/)[1])*.55};}};
const fit=fitText(context,'Uma manchete muito extensa '.repeat(100),{width:952,height:210,maxSize:59,minSize:33});
assert.ok(fit.truncated);
assert.ok(fit.lines.at(-1).endsWith('…'));
assert.ok(fit.lines.length*fit.lineHeight<=210);
assert.ok(fit.lines.every(line=>context.measureText(line).width<=952));
assert.ok(wrapLines(context,'Supercalifragilisticamente'.repeat(10),200).every(line=>context.measureText(line).width<=200));
console.log('Instagram: classificação, cores, nomes, limpeza, ajuste e truncamento de texto OK');
